---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp-secret
  namespace: database
spec:
  encryptedData:
    password: AgAsqjH7Iyo1IM/y2y48D9Ehrjz2xN71kPf95zItsgu1O/kkdc7L22qxNTqy9+UIpctadNv9hSSQP19lJOnlBHKJHmYjj+F2vMbKENJPWvC727ZJvqiUKY/fsPB4jOUQRgFRi4YHYel/CJzOckLyxNvfodefkNKCVa6nUUd+9v6R16ReqR58WYUBTCUyRpz3IMfqUPOMbalE2r3b48QGlZVvTmSPav6vAyVdNr7uXnV8ASyhjK81S4HGSeBM5pkBL48ISVfSnLCFg/mbiPASDLzmXP58NtjU7zS/D2JHn0S1vhh2kHtGcteJ7fAI0pCPz/L7zblNicOZPx/gKGVvtjA4joY/6pVIfJ8iU6eteTJZHFe6MI19LiYZRmX2fLok/cuYVoTiCnlW4gyHNBLCXO7eKCrMshHY1EvhgbRaWYthGK9uHKkgmuq8eumsQNdMXvOLFCjCOW+NowfzhYkQOFFsDUjccgE9+Am0Bt6r3G71Pn1dSHW16UGclxAUo8CSQ6x6V9WpSzRtALQIEK+eRMYCy+R9AAjCDxHzRvk7Qqj9gLzxzS4qTeBWQVsDRKayRVvAA59E0kq4lBBxV8RSgQ8G169oA629/ATZck4QqnPRHSNQ7UjiRrtbkGWWXTuD5z8b/qJWt5X/t4i5NN7XR4s7n7VaZt7iS1gfWROQ8atJneRV7JaYRzeMRSUrn9Bl95ZGIu+dgYSXoP+3GdNLTxof0PT4
  template:
    metadata:
      name: alertmanager-smtp-secret
      namespace: database
    type: Opaque
