---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-creds
  namespace: database
spec:
  encryptedData:
    password: AgAUzgsD4VYhgCfykmI9jogaHOk/zqQ+zpGxpIXtuaxjGCgs2BudUobgmFy4du5TAL/K/44A9d7EGwaDzCJmPx67UV+jWDsJpmZ2r2k0FDfZR9Ugb8OcUJCuz6OMzRiz6jk14vrzeUI5Pavo10YTnJ6DKV9CNhP5McJOLgcH8yNI3JqtAnBKP7U2cZvNPEFsxGm2AGIl+BJ3w87bvl2PWIMDVoGk4Kzbg69L+ZQzdX0GVw0i4QS+YBkU/rU8czwoYWsWzGibavCimKaAYAZst0Py3nGYhOpQGkIl4ckqiphwGqbVybFp8q1AgdPVOVDVgXJaX5o+2uqGgQdZVzgpEa/DNW41gutIExYm57/7BuEs/qqhYSipCqU3Eeuw1a15D0Czb+GvECkBCnrNHtdPuliORaZDxX2JQTLreapFRsf2ARdQgW9H5pWgf3S/rzC9IcYVuNifogCDptxy4D53iSY7EvaEYGqGkY6IDXyjw7NbWmU01heO/oXJo7xFgGjQAbSfqVjb1omBUSNY3VdH3wa6sCfxDIXT7tr2pi2rDKIvRm3lrOSUPt8ohoOIVQ5nJb1yzJ1AAOttY+h4oUxLwe7xdWXUMn2ENKuHSezXVKfC9JYWowejLqnxn4EI9C5eLuBkXMC31hbqMVznVSaaPzXd3aqhsSBEic1Xnv0Tlp6bMcauo5wQn7HoVi6eZnaz/5jG/4glEQtNkMRBfw==
    username: AgA91+fEMEH0gmg5LVO4ovxgRxKQh1nbQh3cy2NDg0rPd/qwV2h9NRBUBVYJQjGmgGxsn+5Dg1yB44dLPdwD52zSQCWXLUgDHTuKEKtWabD1t7cnxV1rxa18E8ibg02UHIbSAM2Egn6oiDcPCgAii7ZIBADADs08imUaxF2kZLYAajg7gKNH1EVJ5JmQEjkqICypemTxuY047/gtHr1O9SNnPjvm1Z5b4VLWmcElH8+UZN445AsfdgWJhzTF5BXzUjzUq1SdMyAOoQRodV3dxK96REccd8hbrnK36O2y8tKAmXEFNRZClk/VEVLRKYggMMp064UY4XPwNs8TXdj+qVpCnd+iLJb5Mg2PllcuwXg4LYxtWV68o/efnCg7XB9ZyQ7DtEFrJuECtt+MhBMT5KmnOehOi6es4ndB31fRIN2eWQL4r9PjuE3QDJxtU+2Cvu+q7Ttp19grnm2LLD9aqMQxW9f1WWCCJI41SdylRJK1VRSORxuiLYiOXaDeY6FtdZyqD5XYHYuKr3x7Tb1AYG1IUu8R/FSz72LgZmpYhi2/v+FMJtd9AIZJqf68HVRAIPz4qQ3Ea22cD5aRktNE6hBobItXg2WslN/UUgGyT2/S4Wox+p6ZDqA4cAUe7LHQAp70svwNwcYbuYK8sCIRO/exNgZFrstnbaKUIfG3P6sZar0n/Bw3Wg6LSLf866tcokAvXwpvFhhGGA==
  template:
    metadata:
      name: db-creds
      namespace: database
    type: Opaque
