apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy-ingress-monitor
  namespace: ingress-controller
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-ingress
  endpoints:
  - port: stat
    path: /metrics
    interval: 15s
