apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kasmweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/aliabbaschadhar/warmwind-argocd-ops"
    targetRevision: HEAD
    path: kasmweb
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
